// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd_2Ib6e7Rzmx4ZbfGwIslLeH-68wkRZU',
    appId: '1:340618108498:web:ca0a9a096a465e4f83498b',
    messagingSenderId: '340618108498',
    projectId: 'stockia-f048c',
    authDomain: 'stockia-f048c.firebaseapp.com',
    storageBucket: 'stockia-f048c.firebasestorage.app',
    measurementId: 'G-81ELCFPWDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKz03AdXBFGnFYgicgTIKqVOlwjjdG6A8',
    appId: '1:340618108498:android:ecf477efa01d408883498b',
    messagingSenderId: '340618108498',
    projectId: 'stockia-f048c',
    storageBucket: 'stockia-f048c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK0MNFfHuqk18PvCLlgsFIvbuPWhMvd1Y',
    appId: '1:340618108498:ios:010facfa0baaf51283498b',
    messagingSenderId: '340618108498',
    projectId: 'stockia-f048c',
    storageBucket: 'stockia-f048c.firebasestorage.app',
    iosClientId: '340618108498-r9b3stuqupqmf14l8bh9qig57gr97qb0.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK0MNFfHuqk18PvCLlgsFIvbuPWhMvd1Y',
    appId: '1:340618108498:ios:010facfa0baaf51283498b',
    messagingSenderId: '340618108498',
    projectId: 'stockia-f048c',
    storageBucket: 'stockia-f048c.firebasestorage.app',
    iosClientId: '340618108498-r9b3stuqupqmf14l8bh9qig57gr97qb0.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd_2Ib6e7Rzmx4ZbfGwIslLeH-68wkRZU',
    appId: '1:340618108498:web:944d407f1f6417bb83498b',
    messagingSenderId: '340618108498',
    projectId: 'stockia-f048c',
    authDomain: 'stockia-f048c.firebaseapp.com',
    storageBucket: 'stockia-f048c.firebasestorage.app',
    measurementId: 'G-LPV03M4H1K',
  );
}
